# Generated by Django 5.0.6 on 2024-07-28 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='doctor',
        ),
    ]
