# Generated by Django 5.0.6 on 2024-07-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_talon'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='talon',
            field=models.ManyToManyField(to='product.talon'),
        ),
    ]
